apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: think-tank-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: think-tank-demo-app
  template:
    metadata:
      labels:
        app: think-tank-demo-app
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: think-tank-demo-app
spec:
  ports:
  - port: 5672
    protocol: TCP
  selector:
    app: think-tank-demo-app